from fastapi import APIRouter, Depends, HTTPException, status
from typing import List, Optional
from database import get_db
from bson import ObjectId
from datetime import datetime
from utils.helpers import serialize_mongo_doc, serialize_mongo_list

router = APIRouter(prefix="/api/technologies", tags=["technologies"])

# ── Enriched Technology Dataset ───────────────────────────────────────────────
TRENDING_STACKS = [
    # ── Frontend ──────────────────────────────────────────────────────────────
    {
        "name": "React", "category": "Frontend", "trend": "hot",
        "icon_emoji": "⚛️", "difficulty": "Intermediate",
        "demand_score": 97, "trending_score": 9.2,
        "version": "18.3.1", "year_introduced": 2013,
        "description": "React is the world's most widely used JavaScript library for building component-based user interfaces. Developed and maintained by Meta, it lets you compose complex UIs from small, isolated pieces called components. React's virtual DOM and one-way data flow make large applications predictable and easy to debug. It powers apps at Meta, Airbnb, Netflix, and thousands of startups.",
        "use_cases": ["Single-Page Applications", "Dashboards", "E-commerce frontends", "Social platforms"],
        "companies": ["Meta", "Netflix", "Airbnb", "Uber", "Twitter"],
        "advantages": ["Huge ecosystem", "Reusable components", "Virtual DOM performance", "Strong community"],
        "tags": ["JavaScript", "UI", "Components"],
        "docs_url": "https://react.dev",
        "website_url": "https://react.dev",
        "github_url": "https://github.com/facebook/react",
        "related": ["Next.js", "TypeScript", "Redux"],
        "career_opportunities": "Frontend Developer, React Developer, Full-Stack Engineer",
        "beginner_tips": "Start with the official docs at react.dev. Build a todo app, then a weather app using an API.",
        "common_mistakes": "Mutating state directly, not understanding the dependency array in useEffect, over-using useEffect.",
        "learning_path": "HTML/CSS → JavaScript → React → Hooks → React Router",
    },
    {
        "name": "Next.js", "category": "Frontend", "trend": "hot",
        "icon_emoji": "▲", "difficulty": "Intermediate",
        "demand_score": 95, "trending_score": 9.4,
        "version": "15.3.4", "year_introduced": 2016,
        "description": "Next.js is the leading full-stack React framework built by Vercel. It provides Server-Side Rendering (SSR), Static Site Generation (SSG), API routes, and the revolutionary App Router with React Server Components. Next.js eliminates the complexity of configuring Webpack, routing, and deployment — you get a production-ready setup out of the box.",
        "use_cases": ["Full-stack web apps", "E-commerce", "Marketing sites", "SaaS dashboards", "Blogs"],
        "companies": ["Vercel", "TikTok", "Twitch", "Hulu", "HashiCorp"],
        "advantages": ["SSR & SSG out of the box", "Built-in image optimization", "API routes", "Edge-ready"],
        "tags": ["React", "SSR", "Full-Stack"],
        "docs_url": "https://nextjs.org/docs",
        "website_url": "https://nextjs.org",
        "github_url": "https://github.com/vercel/next.js",
        "related": ["React", "TypeScript", "Vercel"],
        "career_opportunities": "Full-Stack Developer, Frontend Architect, Next.js Developer",
        "beginner_tips": "Learn React first, then follow the official Next.js tutorial. Focus on the App Router.",
        "common_mistakes": "Confusing Server vs Client Components, not using next/image for optimization.",
        "learning_path": "React → Next.js pages → App Router → Server Components → Deployment",
    },
    {
        "name": "TypeScript", "category": "Frontend", "trend": "hot",
        "icon_emoji": "🔷", "difficulty": "Intermediate",
        "demand_score": 94, "trending_score": 9.3,
        "version": "5.8.3", "year_introduced": 2012,
        "description": "TypeScript is a strongly-typed superset of JavaScript developed by Microsoft. It adds optional static typing, interfaces, generics, and modern JavaScript features that compile down to plain JavaScript. TypeScript dramatically improves code quality, IDE support (autocomplete, refactoring), and catches bugs at compile time rather than runtime. It is now the de facto standard for large-scale JavaScript projects.",
        "use_cases": ["Large codebases", "Team collaboration", "API layer typing", "Library authoring"],
        "companies": ["Microsoft", "Google", "Slack", "Airbnb", "Shopify"],
        "advantages": ["Catches bugs early", "Better IDE support", "Scales to large teams", "Self-documenting code"],
        "tags": ["Static Types", "JavaScript", "Tooling"],
        "docs_url": "https://www.typescriptlang.org/docs/",
        "website_url": "https://www.typescriptlang.org",
        "github_url": "https://github.com/microsoft/TypeScript",
        "related": ["React", "Next.js", "Node.js"],
        "career_opportunities": "TypeScript Developer, Frontend Engineer, Full-Stack Developer",
        "beginner_tips": "Add TypeScript to a JavaScript project gradually. Use 'any' sparingly — the goal is strict typing.",
        "common_mistakes": "Using 'any' everywhere, not using utility types, ignoring tsconfig.json strictness.",
        "learning_path": "JavaScript → TypeScript basics → Generics → Decorators → Advanced patterns",
    },
    {
        "name": "Vue.js", "category": "Frontend", "trend": "rising",
        "icon_emoji": "💚", "difficulty": "Beginner",
        "demand_score": 82, "trending_score": 8.4,
        "version": "3.5.13", "year_introduced": 2014,
        "description": "Vue.js is a progressive JavaScript framework for building UIs and SPAs. Its Composition API and intuitive template syntax make it beginner-friendly while remaining powerful for complex apps. Vue's gentle learning curve and excellent documentation make it a top choice for developers moving from jQuery or for teams wanting a simpler React alternative.",
        "use_cases": ["SPAs", "Admin panels", "Interactive UIs", "CMS frontends"],
        "companies": ["Alibaba", "Xiaomi", "Adobe", "GitLab"],
        "advantages": ["Gentle learning curve", "Flexible architecture", "Excellent docs", "Composition API"],
        "tags": ["JavaScript", "UI", "Composition API"],
        "docs_url": "https://vuejs.org/guide/",
        "website_url": "https://vuejs.org",
        "github_url": "https://github.com/vuejs/core",
        "related": ["Nuxt.js", "Pinia", "Vite"],
        "career_opportunities": "Vue Developer, Frontend Developer, Full-Stack Engineer",
        "beginner_tips": "Start with the official tutorial at vuejs.org. Vue 3 with the Composition API is the modern approach.",
        "common_mistakes": "Mixing Options API and Composition API styles, forgetting to declare reactive state.",
        "learning_path": "HTML/CSS/JS → Vue 3 Basics → Composition API → Vue Router → Pinia",
    },
    # ── Backend ────────────────────────────────────────────────────────────────
    {
        "name": "Node.js", "category": "Backend", "trend": "hot",
        "icon_emoji": "🟢", "difficulty": "Beginner",
        "demand_score": 96, "trending_score": 9.1,
        "version": "22.16.0", "year_introduced": 2009,
        "description": "Node.js is a JavaScript runtime built on Chrome's V8 engine that allows JavaScript to run server-side. Its non-blocking, event-driven architecture makes it ideal for building fast, scalable network applications. Paired with Express or Fastify, Node.js powers millions of REST APIs, real-time apps, and microservices in production.",
        "use_cases": ["REST APIs", "Real-time apps", "CLI tools", "Microservices", "WebSockets"],
        "companies": ["Netflix", "LinkedIn", "Walmart", "Uber", "NASA"],
        "advantages": ["Same language on client+server", "Massive npm ecosystem", "Non-blocking I/O", "Active community"],
        "tags": ["JavaScript", "Runtime", "APIs"],
        "docs_url": "https://nodejs.org/docs",
        "website_url": "https://nodejs.org",
        "github_url": "https://github.com/nodejs/node",
        "related": ["Express.js", "TypeScript", "MongoDB"],
        "career_opportunities": "Node.js Developer, Backend Developer, Full-Stack Engineer",
        "beginner_tips": "Learn async/await and the event loop. Build a REST API with Express.js first.",
        "common_mistakes": "Blocking the event loop with synchronous code, not handling errors in async functions.",
        "learning_path": "JavaScript → Node basics → npm → Express.js → Databases → Deployment",
    },
    {
        "name": "FastAPI", "category": "Backend", "trend": "hot",
        "icon_emoji": "⚡", "difficulty": "Intermediate",
        "demand_score": 90, "trending_score": 9.3,
        "version": "0.115.12", "year_introduced": 2018,
        "description": "FastAPI is a modern, high-performance Python web framework for building APIs. It's based on Python type hints and OpenAPI, automatically generating interactive docs (Swagger UI) for every endpoint. FastAPI is asynchronous by design and is the fastest Python framework available in benchmarks, making it the go-to choice for ML model serving, microservices, and internal APIs.",
        "use_cases": ["REST APIs", "ML model serving", "Microservices", "Data pipelines", "Admin APIs"],
        "companies": ["Microsoft", "Uber", "Netflix", "Explosion AI"],
        "advantages": ["Auto-generated OpenAPI docs", "Async support", "Type-safe", "Excellent performance"],
        "tags": ["Python", "Async", "OpenAPI"],
        "docs_url": "https://fastapi.tiangolo.com",
        "website_url": "https://fastapi.tiangolo.com",
        "github_url": "https://github.com/tiangolo/fastapi",
        "related": ["Python", "Pydantic", "SQLAlchemy", "Uvicorn"],
        "career_opportunities": "Backend Developer, Python Developer, MLOps Engineer",
        "beginner_tips": "Learn Python type hints first. FastAPI uses them heavily. Start with the official tutorial.",
        "common_mistakes": "Not using Pydantic models for request/response, blocking async endpoints with sync operations.",
        "learning_path": "Python → Type hints → FastAPI basics → Pydantic → Async → Databases",
    },
    {
        "name": "Go (Golang)", "category": "Backend", "trend": "hot",
        "icon_emoji": "🐹", "difficulty": "Intermediate",
        "demand_score": 89, "trending_score": 9.4,
        "version": "1.24.4", "year_introduced": 2009,
        "description": "Go is a compiled, statically typed language created by Google. It produces single binary executables, has built-in concurrency via goroutines, and compiles in seconds. Go is the language of choice for building cloud infrastructure, microservices, and CLI tools that need high performance and low memory footprint. Docker, Kubernetes, and Terraform are all written in Go.",
        "use_cases": ["Microservices", "Cloud-native apps", "CLI tools", "Network services", "Databases"],
        "companies": ["Google", "Cloudflare", "Docker", "Stripe", "Dropbox"],
        "advantages": ["Lightning-fast compilation", "Built-in concurrency", "Low memory usage", "Simple syntax"],
        "tags": ["Compiled", "Concurrency", "Cloud-native"],
        "docs_url": "https://go.dev/doc/",
        "website_url": "https://go.dev",
        "github_url": "https://github.com/golang/go",
        "related": ["Docker", "Kubernetes", "gRPC"],
        "career_opportunities": "Go Developer, Backend Engineer, Cloud Infrastructure Engineer",
        "beginner_tips": "Start with 'A Tour of Go' on go.dev. Focus on goroutines and channels — they're Go's superpower.",
        "common_mistakes": "Ignoring error returns, overusing goroutines, not understanding Go's interface system.",
        "learning_path": "Go Tour → Standard Library → Goroutines → HTTP servers → gRPC → Kubernetes",
    },
    {
        "name": "GraphQL", "category": "Backend", "trend": "rising",
        "icon_emoji": "🔗", "difficulty": "Intermediate",
        "demand_score": 80, "trending_score": 8.5,
        "version": "16.10.0", "year_introduced": 2015,
        "description": "GraphQL is a declarative query language for APIs developed by Meta. Instead of multiple REST endpoints, clients send a single query describing exactly the data they need. This eliminates over-fetching (too much data) and under-fetching (too many requests). GraphQL's strongly typed schema acts as a contract between frontend and backend teams.",
        "use_cases": ["Mobile apps", "Complex UIs", "BFF pattern", "API aggregation", "Real-time subscriptions"],
        "companies": ["Meta", "GitHub", "Shopify", "Twitter", "Yelp"],
        "advantages": ["No over/under fetching", "Strongly typed schema", "Single endpoint", "Introspection"],
        "tags": ["API", "Query Language", "Schema"],
        "docs_url": "https://graphql.org/learn/",
        "website_url": "https://graphql.org",
        "github_url": "https://github.com/graphql/graphql-js",
        "related": ["Apollo Client", "Prisma", "REST"],
        "career_opportunities": "Backend Developer, API Engineer, Full-Stack Developer",
        "beginner_tips": "Learn REST APIs first. Then understand GraphQL's type system and resolver pattern.",
        "common_mistakes": "Not batching queries with DataLoader (N+1 problem), exposing too much in schema.",
        "learning_path": "REST → GraphQL spec → Apollo Server → Resolvers → Subscriptions → Federation",
    },
    # ── DevOps ─────────────────────────────────────────────────────────────────
    {
        "name": "Docker", "category": "DevOps", "trend": "hot",
        "icon_emoji": "🐳", "difficulty": "Beginner",
        "demand_score": 96, "trending_score": 9.5,
        "version": "27.5.1", "year_introduced": 2013,
        "description": "Docker is the standard containerization platform that packages applications and all their dependencies into portable, consistent containers. A Docker container runs identically on a developer's MacBook, a CI server, and a cloud VM — eliminating the 'it works on my machine' problem forever. Docker is now a mandatory skill for virtually every software engineering role.",
        "use_cases": ["Application packaging", "Microservices", "CI/CD pipelines", "Development environments"],
        "companies": ["Almost every tech company", "AWS", "Google Cloud", "Azure"],
        "advantages": ["Consistent environments", "Fast startup", "Lightweight", "Huge image ecosystem (Docker Hub)"],
        "tags": ["Containers", "Images", "Isolation"],
        "docs_url": "https://docs.docker.com",
        "website_url": "https://www.docker.com",
        "github_url": "https://github.com/docker/docker-ce",
        "related": ["Kubernetes", "Docker Compose", "GitHub Actions"],
        "career_opportunities": "DevOps Engineer, Cloud Engineer, Backend Developer",
        "beginner_tips": "Start by containerizing a simple Node.js or Python app. Then learn docker-compose for multi-container apps.",
        "common_mistakes": "Running as root inside containers, storing data in containers instead of volumes.",
        "learning_path": "Linux basics → Docker run/build → Dockerfile → Docker Compose → Registries",
    },
    {
        "name": "Kubernetes", "category": "DevOps", "trend": "hot",
        "icon_emoji": "☸️", "difficulty": "Advanced",
        "demand_score": 91, "trending_score": 9.6,
        "version": "1.33.1", "year_introduced": 2014,
        "description": "Kubernetes (K8s) is the industry-standard container orchestration system for automating deployment, scaling, and management of containerized applications. Originally designed by Google, it handles load balancing, service discovery, storage orchestration, and self-healing. Every major cloud provider offers managed Kubernetes (EKS, GKE, AKS).",
        "use_cases": ["Container orchestration", "Microservices at scale", "Auto-scaling", "Blue/green deployments"],
        "companies": ["Google", "Spotify", "Airbnb", "Salesforce", "Goldman Sachs"],
        "advantages": ["Auto-scaling", "Self-healing", "Rolling deployments", "Cloud-agnostic"],
        "tags": ["Orchestration", "Scaling", "YAML"],
        "docs_url": "https://kubernetes.io/docs/",
        "website_url": "https://kubernetes.io",
        "github_url": "https://github.com/kubernetes/kubernetes",
        "related": ["Docker", "Helm", "ArgoCD", "Terraform"],
        "career_opportunities": "DevOps Engineer, Platform Engineer, Site Reliability Engineer (SRE)",
        "beginner_tips": "Learn Docker first. Use minikube or kind to run a local cluster. Focus on Pods, Services, Deployments.",
        "common_mistakes": "Not setting resource limits/requests, ignoring RBAC security, not using Namespaces.",
        "learning_path": "Docker → kubectl basics → Pods/Services → Deployments → Helm → GitOps",
    },
    {
        "name": "Terraform", "category": "DevOps", "trend": "hot",
        "icon_emoji": "🏗️", "difficulty": "Intermediate",
        "demand_score": 87, "trending_score": 8.9,
        "version": "1.12.2", "year_introduced": 2014,
        "description": "Terraform by HashiCorp is the leading Infrastructure as Code (IaC) tool. It lets you define cloud infrastructure — VMs, networks, databases, load balancers — in HCL configuration files and provision them consistently and repeatably. Terraform supports 1000+ providers including AWS, GCP, Azure, and Kubernetes.",
        "use_cases": ["Cloud infrastructure provisioning", "Multi-cloud management", "Infrastructure versioning"],
        "companies": ["HashiCorp", "Atlassian", "Slack", "Stripe"],
        "advantages": ["Declarative syntax", "State management", "Multi-cloud", "Module reuse"],
        "tags": ["IaC", "Cloud", "HCL"],
        "docs_url": "https://developer.hashicorp.com/terraform/docs",
        "website_url": "https://www.terraform.io",
        "github_url": "https://github.com/hashicorp/terraform",
        "related": ["AWS", "Kubernetes", "Ansible", "GitHub Actions"],
        "career_opportunities": "DevOps Engineer, Cloud Architect, Platform Engineer",
        "beginner_tips": "Start with the official Terraform tutorials on AWS. Learn the plan/apply workflow.",
        "common_mistakes": "Hardcoding credentials, not using remote state, circular dependencies between modules.",
        "learning_path": "Cloud basics → HCL syntax → Plan/Apply → Modules → Remote state → CI/CD integration",
    },
    # ── Database ───────────────────────────────────────────────────────────────
    {
        "name": "PostgreSQL", "category": "Database", "trend": "hot",
        "icon_emoji": "🐘", "difficulty": "Intermediate",
        "demand_score": 95, "trending_score": 9.2,
        "version": "17.5", "year_introduced": 1996,
        "description": "PostgreSQL is the world's most advanced open-source relational database system. It supports SQL plus JSON, full-text search, PostGIS for geospatial data, logical replication, custom extensions, and advanced indexing. PostgreSQL's ACID compliance, reliability, and feature set make it the default choice for modern applications ranging from startups to enterprises.",
        "use_cases": ["Transactional data", "Analytics", "SaaS backends", "Geospatial apps", "Time-series"],
        "companies": ["Apple", "Spotify", "Instagram", "GitLab", "Supabase"],
        "advantages": ["ACID compliant", "Extensible", "JSON support", "Advanced indexing", "MVCC"],
        "tags": ["SQL", "ACID", "Relational"],
        "docs_url": "https://www.postgresql.org/docs/",
        "website_url": "https://www.postgresql.org",
        "github_url": "https://github.com/postgres/postgres",
        "related": ["Prisma", "Supabase", "Redis", "SQLAlchemy"],
        "career_opportunities": "Database Administrator, Backend Developer, Data Engineer",
        "beginner_tips": "Learn basic SQL first. Then practice with real data and explore PostgreSQL-specific features.",
        "common_mistakes": "Not using indexes, using SELECT *, not wrapping related operations in transactions.",
        "learning_path": "SQL basics → CRUD → Joins → Indexes → Transactions → Query optimization",
    },
    {
        "name": "MongoDB", "category": "Database", "trend": "hot",
        "icon_emoji": "🍃", "difficulty": "Beginner",
        "demand_score": 88, "trending_score": 8.8,
        "version": "8.0.9", "year_introduced": 2009,
        "description": "MongoDB is the world's leading document-oriented NoSQL database. Data is stored as flexible JSON-like BSON documents rather than rigid rows and columns, making it ideal for rapidly evolving schemas. MongoDB Atlas offers a managed cloud service with full-text search, real-time analytics, and automatic scaling.",
        "use_cases": ["Flexible schemas", "Content management", "User profiles", "IoT data", "Catalogs"],
        "companies": ["Lyft", "Forbes", "Bosch", "Verizon", "CERN"],
        "advantages": ["Schema flexibility", "Horizontal scaling", "Rich query language", "Atlas cloud platform"],
        "tags": ["NoSQL", "Documents", "JSON"],
        "docs_url": "https://www.mongodb.com/docs/",
        "website_url": "https://www.mongodb.com",
        "github_url": "https://github.com/mongodb/mongo",
        "related": ["Mongoose", "PostgreSQL", "Redis"],
        "career_opportunities": "Backend Developer, Full-Stack Developer, Data Engineer",
        "beginner_tips": "Learn the document model. Understand when MongoDB is better than SQL (and when it isn't).",
        "common_mistakes": "Using MongoDB when relational data is needed, not using indexes, embedding too much data.",
        "learning_path": "JSON basics → CRUD → Queries → Aggregation → Indexes → Atlas",
    },
    # ── AI / ML ────────────────────────────────────────────────────────────────
    {
        "name": "LangChain", "category": "AI / ML", "trend": "hot",
        "icon_emoji": "🦜", "difficulty": "Intermediate",
        "demand_score": 93, "trending_score": 9.6,
        "version": "0.3.26", "year_introduced": 2022,
        "description": "LangChain is the dominant framework for building production LLM applications. It provides composable building blocks for chains, agents, memory, RAG (Retrieval-Augmented Generation) pipelines, and tool-calling. LangChain abstracts over dozens of LLM providers and vector databases, making it the fastest way to ship AI features into real products.",
        "use_cases": ["Chatbots", "RAG pipelines", "AI agents", "Document Q&A", "Code generation tools"],
        "companies": ["Salesforce", "Klarna", "Elastic", "Moody's"],
        "advantages": ["Provider-agnostic", "Composable chains", "Built-in RAG support", "Agent framework"],
        "tags": ["LLM", "Agents", "RAG"],
        "docs_url": "https://python.langchain.com/docs/",
        "website_url": "https://www.langchain.com",
        "github_url": "https://github.com/langchain-ai/langchain",
        "related": ["OpenAI API", "Pinecone", "Hugging Face", "LangGraph"],
        "career_opportunities": "AI Engineer, LLM Engineer, ML Platform Engineer",
        "beginner_tips": "Start with a simple RAG app — load a PDF, embed it, and answer questions about it.",
        "common_mistakes": "Not chunking documents properly, ignoring token limits, not evaluating RAG quality.",
        "learning_path": "Python → OpenAI API → LangChain basics → Chains → Agents → RAG → LangGraph",
    },
    {
        "name": "PyTorch", "category": "AI / ML", "trend": "hot",
        "icon_emoji": "🔥", "difficulty": "Advanced",
        "demand_score": 91, "trending_score": 9.4,
        "version": "2.7.1", "year_introduced": 2016,
        "description": "PyTorch is the dominant deep learning framework used by researchers and production ML teams worldwide. Its dynamic computation graph (eager mode) enables intuitive debugging and flexible model architectures. PyTorch powers landmark AI models including GPT, LLaMA, DALL-E, and Stable Diffusion. It's the language of AI research.",
        "use_cases": ["Deep learning research", "LLM fine-tuning", "Computer vision", "NLP", "Generative AI"],
        "companies": ["Meta", "OpenAI", "Stability AI", "Hugging Face", "Tesla"],
        "advantages": ["Dynamic computation graph", "Pythonic API", "Large research community", "TorchScript production"],
        "tags": ["Deep Learning", "Python", "GPU"],
        "docs_url": "https://pytorch.org/docs/",
        "website_url": "https://pytorch.org",
        "github_url": "https://github.com/pytorch/pytorch",
        "related": ["Hugging Face", "NumPy", "CUDA", "Lightning"],
        "career_opportunities": "ML Engineer, AI Researcher, Deep Learning Engineer",
        "beginner_tips": "Learn NumPy first. Then learn tensor operations in PyTorch before building neural networks.",
        "common_mistakes": "Forgetting to zero gradients before backward pass, not moving tensors to GPU when available.",
        "learning_path": "Python → NumPy → PyTorch tensors → Autograd → Neural networks → CNNs → Transformers",
    },
    {
        "name": "Hugging Face", "category": "AI / ML", "trend": "hot",
        "icon_emoji": "🤗", "difficulty": "Intermediate",
        "demand_score": 92, "trending_score": 9.3,
        "version": "4.52.4", "year_introduced": 2018,
        "description": "Hugging Face is the central hub for open-source AI — a GitHub for machine learning models, datasets, and tools. The Transformers library provides access to thousands of pre-trained models (BERT, GPT-2, LLaMA, Mistral) and the Datasets library simplifies data management. Hugging Face is essential for anyone working with NLP, computer vision, or generative AI.",
        "use_cases": ["Model fine-tuning", "NLP tasks", "Text generation", "Image models", "Model deployment"],
        "companies": ["Google", "Microsoft", "Amazon", "Grammarly", "Bloomberg"],
        "advantages": ["Largest model hub", "Easy fine-tuning", "Multi-framework (PyTorch/TF)", "Active community"],
        "tags": ["Models", "Transformers", "Open Source"],
        "docs_url": "https://huggingface.co/docs",
        "website_url": "https://huggingface.co",
        "github_url": "https://github.com/huggingface/transformers",
        "related": ["PyTorch", "LangChain", "OpenAI API"],
        "career_opportunities": "ML Engineer, NLP Engineer, AI Researcher",
        "beginner_tips": "Load a pre-trained model with the pipeline() API in 5 lines. Then explore fine-tuning with Trainer.",
        "common_mistakes": "Not checking model licenses, loading models without quantization on small GPUs.",
        "learning_path": "Python → PyTorch → Transformers library → Fine-tuning → Spaces → Inference API",
    },
    {
        "name": "OpenAI API", "category": "AI / ML", "trend": "hot",
        "icon_emoji": "🤖", "difficulty": "Beginner",
        "demand_score": 97, "trending_score": 9.8,
        "version": "1.x (Latest)", "year_introduced": 2020,
        "description": "The OpenAI API provides programmatic access to GPT-4o, o1, image generation (DALL-E 3), speech-to-text (Whisper), and embeddings. It's the fastest way to integrate cutting-edge AI into any product. With structured outputs, function calling, and vision capabilities, the OpenAI API enables a new class of intelligent applications.",
        "use_cases": ["Chatbots", "Code assistants", "Text summarization", "Image generation", "Document analysis"],
        "companies": ["Microsoft", "Salesforce", "HubSpot", "Notion", "Duolingo"],
        "advantages": ["State-of-the-art models", "Simple REST API", "Function calling", "Vision + audio"],
        "tags": ["GPT-4o", "Embeddings", "Vision"],
        "docs_url": "https://platform.openai.com/docs",
        "website_url": "https://platform.openai.com",
        "github_url": "https://github.com/openai/openai-python",
        "related": ["LangChain", "Pinecone", "Anthropic Claude", "OpenRouter"],
        "career_opportunities": "AI Engineer, Prompt Engineer, Product Engineer",
        "beginner_tips": "Start with the Quickstart and build a simple chatbot. Then explore function calling.",
        "common_mistakes": "Not handling rate limits, storing API keys in code (use env vars), not caching responses.",
        "learning_path": "Python → API basics → Chat completions → Function calling → Embeddings → Fine-tuning",
    },
    # ── Mobile ─────────────────────────────────────────────────────────────────
    {
        "name": "React Native", "category": "Mobile", "trend": "hot",
        "icon_emoji": "📱", "difficulty": "Intermediate",
        "demand_score": 85, "trending_score": 8.7,
        "version": "0.79.3", "year_introduced": 2015,
        "description": "React Native lets you build native iOS and Android apps using React and JavaScript. You write one codebase and ship to both platforms, sharing up to 90% of code. With Expo, React Native becomes even more accessible — you can build, deploy, and update apps without touching native code. Major apps like Facebook, Instagram, and Shopify use React Native in production.",
        "use_cases": ["Cross-platform mobile apps", "MVPs", "Consumer apps", "Internal tools"],
        "companies": ["Meta", "Shopify", "Discord", "Walmart", "Bloomberg"],
        "advantages": ["Code sharing across platforms", "Large React ecosystem", "Hot reloading", "Native modules"],
        "tags": ["iOS", "Android", "JavaScript"],
        "docs_url": "https://reactnative.dev/docs/",
        "website_url": "https://reactnative.dev",
        "github_url": "https://github.com/facebook/react-native",
        "related": ["Expo", "React", "TypeScript"],
        "career_opportunities": "Mobile Developer, React Native Developer, Cross-Platform Engineer",
        "beginner_tips": "Learn React first. Use Expo to get started without Xcode/Android Studio complexity.",
        "common_mistakes": "Not using StyleSheet, overusing useState instead of state management, ignoring performance.",
        "learning_path": "React → React Native basics → Expo → Navigation → State Management → Native Modules",
    },
    {
        "name": "Flutter", "category": "Mobile", "trend": "hot",
        "icon_emoji": "🦋", "difficulty": "Intermediate",
        "demand_score": 82, "trending_score": 8.6,
        "version": "3.32.4", "year_introduced": 2018,
        "description": "Flutter is Google's UI toolkit for building natively compiled applications for mobile, web, and desktop from a single Dart codebase. Flutter's own rendering engine draws every pixel, meaning apps look identical on all platforms and perform at 60/120fps. Flutter has the largest contributor community of any cross-platform framework.",
        "use_cases": ["Cross-platform apps", "Design-heavy UIs", "MVPs", "Enterprise apps"],
        "companies": ["Google", "Alibaba", "BMW", "eBay", "Nubank"],
        "advantages": ["Pixel-perfect UI", "60/120fps performance", "Single codebase", "Rich widget library"],
        "tags": ["Dart", "Cross-Platform", "UI"],
        "docs_url": "https://docs.flutter.dev",
        "website_url": "https://flutter.dev",
        "github_url": "https://github.com/flutter/flutter",
        "related": ["Dart", "Firebase", "Riverpod"],
        "career_opportunities": "Flutter Developer, Mobile Engineer, Cross-Platform Developer",
        "beginner_tips": "Learn Dart first (it's quick). Build the counter app, then a shopping cart. Use the official Flutter codelabs.",
        "common_mistakes": "Not using const constructors, overusing StatefulWidget, deeply nested widget trees.",
        "learning_path": "Dart → Flutter basics → Widgets → State Management → Navigation → Firebase",
    },
    # ── Security ───────────────────────────────────────────────────────────────
    {
        "name": "OWASP Top 10", "category": "Security", "trend": "stable",
        "icon_emoji": "🛡️", "difficulty": "Intermediate",
        "demand_score": 88, "trending_score": 8.5,
        "version": "2021 Edition", "year_introduced": 2001,
        "description": "The OWASP Top 10 is the authoritative reference for the most critical web application security risks, published by the Open Web Application Security Project. Every developer must understand these vulnerabilities: Injection, Broken Authentication, Sensitive Data Exposure, XSS, and more. Understanding OWASP is mandatory for building secure software and for most security certifications.",
        "use_cases": ["Secure coding practices", "Security audits", "Penetration testing", "DevSecOps"],
        "companies": ["All organizations with web applications"],
        "advantages": ["Industry standard", "Free resource", "Practical and actionable", "Widely referenced"],
        "tags": ["Web Security", "Vulnerabilities", "Standards"],
        "docs_url": "https://owasp.org/www-project-top-ten/",
        "website_url": "https://owasp.org",
        "github_url": "https://github.com/OWASP/Top10",
        "related": ["BurpSuite", "Vault", "CSP", "JWT"],
        "career_opportunities": "Security Engineer, Penetration Tester, AppSec Engineer",
        "beginner_tips": "Read through all 10 vulnerabilities with real-world examples. Then try DVWA or HackTheBox.",
        "common_mistakes": "Only studying theory without practicing exploits in safe environments.",
        "learning_path": "Networking basics → HTTP → OWASP Top 10 → DVWA → BurpSuite → Bug bounty",
    },
    # ── Emerging ───────────────────────────────────────────────────────────────
    {
        "name": "WebAssembly (Wasm)", "category": "Emerging", "trend": "rising",
        "icon_emoji": "🧩", "difficulty": "Advanced",
        "demand_score": 65, "trending_score": 8.3,
        "version": "2.0", "year_introduced": 2019,
        "description": "WebAssembly (Wasm) is a low-level binary format that runs at near-native speed in the browser and server environments. It allows languages like C, Rust, and Go to be compiled and run in the browser, enabling use cases like video editing, 3D games, and cryptography that are impossible with JavaScript alone. Wasm is also expanding into cloud and edge computing.",
        "use_cases": ["Browser-based games", "Video/audio processing", "Cryptography", "Edge computing"],
        "companies": ["Cloudflare", "Figma", "AutoCAD", "Google Earth"],
        "advantages": ["Near-native performance", "Language-agnostic", "Sandboxed security", "Growing ecosystem"],
        "tags": ["Browser", "Performance", "Binary"],
        "docs_url": "https://developer.mozilla.org/en-US/docs/WebAssembly",
        "website_url": "https://webassembly.org",
        "github_url": "https://github.com/WebAssembly/spec",
        "related": ["Rust", "Go", "Emscripten"],
        "career_opportunities": "Systems Engineer, Browser Engineer, Edge Computing Engineer",
        "beginner_tips": "Start by compiling a simple C function to Wasm and calling it from JavaScript.",
        "common_mistakes": "Thinking Wasm replaces JavaScript — it complements it for performance-critical tasks.",
        "learning_path": "C or Rust → Emscripten/wasm-pack → Wasm basics → WASI → Edge deployment",
    },
    {
        "name": "Rust", "category": "Emerging", "trend": "rising",
        "icon_emoji": "🦀", "difficulty": "Advanced",
        "demand_score": 78, "trending_score": 9.1,
        "version": "1.87.0", "year_introduced": 2015,
        "description": "Rust is a systems programming language that achieves memory safety without a garbage collector, through its revolutionary ownership system. It's blazing fast, prevents entire classes of bugs at compile time, and is the most loved language in Stack Overflow's survey for 10 consecutive years. Rust is used in OS kernels (Linux, Windows), browsers, databases, WebAssembly, and increasingly in backend services.",
        "use_cases": ["Systems programming", "WebAssembly", "CLI tools", "Database engines", "Embedded systems"],
        "companies": ["Amazon", "Microsoft", "Google", "Discord", "Cloudflare"],
        "advantages": ["Memory safety without GC", "Zero-cost abstractions", "Fearless concurrency", "Great tooling"],
        "tags": ["Systems", "Memory Safety", "Performance"],
        "docs_url": "https://doc.rust-lang.org/book/",
        "website_url": "https://www.rust-lang.org",
        "github_url": "https://github.com/rust-lang/rust",
        "related": ["WebAssembly", "C++", "Go"],
        "career_opportunities": "Systems Engineer, Embedded Developer, WebAssembly Engineer, Blockchain Developer",
        "beginner_tips": "Read 'The Rust Book' (free online). Accept that ownership is confusing at first — it will click.",
        "common_mistakes": "Fighting the borrow checker instead of understanding it. Start simple, don't jump to async first.",
        "learning_path": "C basics → The Rust Book → Ownership → Structs/Traits → Error handling → Async",
    },
    {
        "name": "Solidity", "category": "Emerging", "trend": "stable",
        "icon_emoji": "💎", "difficulty": "Intermediate",
        "demand_score": 62, "trending_score": 7.9,
        "version": "0.8.30", "year_introduced": 2014,
        "description": "Solidity is a statically typed, curly-braces programming language designed for writing smart contracts on Ethereum and EVM-compatible blockchains. Smart contracts are self-executing programs stored on the blockchain that automate agreements without intermediaries. Solidity powers DeFi protocols with billions in TVL, NFT marketplaces, and DAOs.",
        "use_cases": ["DeFi protocols", "NFT platforms", "DAOs", "Token contracts", "On-chain games"],
        "companies": ["Uniswap", "OpenSea", "Aave", "Compound", "MakerDAO"],
        "advantages": ["EVM compatible", "Mature ecosystem", "Hardhat & Foundry tooling", "Auditing culture"],
        "tags": ["Blockchain", "EVM", "DeFi"],
        "docs_url": "https://docs.soliditylang.org",
        "website_url": "https://soliditylang.org",
        "github_url": "https://github.com/ethereum/solidity",
        "related": ["Ethereum", "Hardhat", "Foundry", "OpenZeppelin"],
        "career_opportunities": "Smart Contract Developer, Blockchain Engineer, Security Auditor",
        "beginner_tips": "Start on Remix IDE — no setup needed. Build an ERC-20 token using OpenZeppelin's contracts.",
        "common_mistakes": "Not understanding gas optimization, reentrancy vulnerabilities, integer overflow.",
        "learning_path": "Blockchain basics → Ethereum → Solidity syntax → ERC standards → Hardhat → Security auditing",
    },
]

@router.get("/")
async def get_technologies(
    category: Optional[str] = None,
    db = Depends(get_db)
):
    """Fetch the full enriched catalog of technologies"""
    count = await db.technologies.count_documents({"year": 2026})
    if count < len(TRENDING_STACKS):
        await db.technologies.delete_many({"year": 2026})
        await db.technologies.insert_many([{**t, "year": 2026, "created_at": datetime.utcnow()} for t in TRENDING_STACKS])

    query = {"year": 2026}
    if category and category != "All":
        query["category"] = category

    cursor = db.technologies.find(query).sort("trending_score", -1)
    techs = await cursor.to_list(length=100)

    return serialize_mongo_list(techs)

@router.get("/categories")
async def get_technology_categories(db = Depends(get_db)):
    """Fetch distinct categories"""
    categories = await db.technologies.distinct("category", {"year": 2026})
    return sorted(categories)

@router.get("/{tech_id}")
async def get_technology_details(tech_id: str, db = Depends(get_db)):
    """Fetch deep-dive information for a specific technology"""
    tech = await db.technologies.find_one({"_id": ObjectId(tech_id)})
    if not tech:
        raise HTTPException(status_code=404, detail="Technology not found")
    return serialize_mongo_doc(tech)
